name: flickit-keycloak ci-cd

on:
  push:
    tags:
      - "v*"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.TAG.outputs.tag }}
    permissions:
      contents: read
      packages: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: TAG
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/avansoft/flickit-keycloak
         
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  darkube_deploy_keycloak-test:
    needs: build-push-image
    container: hamravesh/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:  
      - name: darkube-cli deploy
        run: |          
          darkube deploy --token ${{ secrets.DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13}}
          --app-id ${{ secrets.APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }} --image-tag ${{needs.build-push-image.outputs.TAG}}
          --job-id ${{github.run_id}}
      
