name: flickit-keycloak ci-cd

on:
  push:
    branches: ['main']
    paths: ['.github/workflows/**', 'docker-context/**']

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: write

jobs:
  build_and_push_image_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: |
            ghcr.io/avansoft/flickit-keycloak:${{ env.SHA }}
            
  darkube_deploy_keycloak-test:
    container: hamravesh/darkube-cli:v1.1
    needs: build_and_push_image_to_ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: darkube-cli deploy
        run: |
          darkube deploy --token ${{ secrets.DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }}
          --app-id ${{ secrets.APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }} --image-tag ${{ env.SHA }}}
          --job-id ${{github.run_id}}
