name: flickit-keycloak ci-cd

on:
  push:
    branches: ['main']
    paths: ['.github/workflows/**', 'docker-context/**']



jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/avansoft/flickit-keycloak
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: darkube-cli deploy
        run: |
          curl -X PUT 'https://api.console.hamravesh.ir/api/v1/darkube/apps/update_from_cli/' 
          -H 'Content-Type: application/json' 
          -d '{"trigger_deploy_token": "${{ secrets.DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13}}",
          "app_id": "${{ secrets.APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }}", "image_tag": "${{ steps.meta.outputs.tags }}"}'
      
