name: flickit-keycloak ci-cd

on:
  push:
    tags:
      - "v*"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.TAG.outputs.tag }}
    permissions:
      contents: read
      packages: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: TAG
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/avansoft/flickit-keycloak
         
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  darkube_deploy_keycloak-test:
    needs: build-push-image
    container: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:  
      - name: darkube-cli deploy
        run: darkube deploy --ref main --token ${DARKUBE_DEPLOY_TOKEN} --app-id ${DARKUBE_APP_ID}  --image-tag "${TAG}" --job-id "$GITHUB_RUN_ID" --stateless-app true
        env:
          DARKUBE_DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13}}
          DARKUBE_APP_ID: ${{ secrets.APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }}
          TAG: ${{needs.build-push-image.outputs.TAG}}
      
