name: flickit-keycloak ci-cd

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: write

jobs:
  build_and_push_image_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: |
            ghcr.io/avansoft/flickit-keycloak:1.0

  darkube_build_keycloak-test:
    container: hamravesh/darkube-cli:v1.1
    runs-on: ubuntu-latest
    steps:
      - env:
          IMAGE_NAME: ghcr.io/avansoft/flickit-keycloak
        name: darkube-cli build & push
        run: ' |

        darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}--workdir
        . --file ./Dockerfile --build-context . '
  darkube_deploy_keycloak-test:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_keycloak-test_flickit-test_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
      - name: darkube-cli deploy
        run: ' |

        darkube deploy --token ${DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13}
        --app-id ${APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13} --image-tag ${GITHUB_SHA:0:7}
        --job-id ${GITHUB_RUN_ID}'
