name: flickit-keycloak ci-cd

on:
  push:
    tags:
      - "v*.*"

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/avansoft/flickit-keycloak
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker-context
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  darkube_deploy_keycloak-test:
    container: hamravesh/darkube-cli:v1.1
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:  
      - name: darkube-cli deploy
        run: |          
          darkube deploy --token ${{ secrets.DEPLOY_TOKEN_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13}}
          --app-id ${{ secrets.APP_ID_KEYCLOAK_TEST_FLICKIT_TEST_HAMRAVESH_C13 }} --image-tag ${{github.ref_name}}
          --job-id ${{github.run_id}}
      
